import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  // Carousel checks should not depend on the unrelated external 3D scene.
  await page.route('**/embedded-scene-mount-*.js', route => route.fulfill({
    contentType: 'text/javascript',
    body: 'export function mountScene(target, scene, ready) { queueMicrotask(ready); return { setPaused() {}, dispose() {} }; }'
  }))
})

test('Lab opens only on request and its native disclosure works by keyboard', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const lab = page.locator('.embedded-lab')
  const button = page.locator('[data-lab-trigger]')
  await expect(button).toHaveAttribute('data-slot', 'liquid-button')
  await expect(page.locator('.embedded-intro [data-lab-trigger]')).toHaveCount(1)
  await expect(lab).not.toHaveAttribute('open')
  await expect(lab.getByRole('heading', { name: 'Lab de Embarcados', exact: true })).not.toBeVisible()
  await button.click()
  await expect(lab).toHaveAttribute('open', '')
  await expect(button).toHaveAttribute('aria-expanded', 'true')
  await expect(lab.getByRole('heading', { name: 'Lab de Embarcados', exact: true })).toBeVisible()
  await expect(lab.locator('.telemetry-path')).toBeVisible()
  await expect(lab.locator('.embedded-lab-content')).toHaveCSS('animation-name', 'none')
  await button.focus()
  await button.press('Enter')
  await expect(lab).not.toHaveAttribute('open')
})

test('carousels cycle, handle rapid direction changes and preserve project links', async ({ page }) => {
  test.setTimeout(60000)
  await page.goto('/')
  const carousel = page.getByRole('region', { name: 'Projetos', exact: true }).and(page.locator('[data-squeeze-carousel]'))
  await expect(carousel).toHaveAttribute('data-sq-ready', 'true')
  await expect(carousel.getByRole('tabpanel', { name: 'Hindsight', exact: true })).toContainText('Hackathon · IBM TechXchange')
  const next = carousel.getByRole('button', { name: 'Próximo projeto' })
  const previous = carousel.getByRole('button', { name: 'Projeto anterior' })
  await next.click()
  await expect(carousel).toHaveAttribute('data-sq-index', '1')
  await previous.click()
  await previous.click()
  await expect(carousel).toHaveAttribute('data-sq-index', '3')
  await next.click()
  await expect(carousel).toHaveAttribute('data-sq-index', '0')
  await expect(carousel.getByRole('link', { name: 'Estudo de caso', exact: true })).toHaveAttribute('href', '/projetos/hindsight/')
  await carousel.getByRole('button', { name: 'Todos os projetos', exact: true }).click()
  const archive = carousel
  const count = await archive.locator('[data-sq-tab]').count()
  const visited = new Set<string>()
  for (let i = 0; i < count; i++) {
    const panel = archive.getByRole('tabpanel')
    await expect(panel).toHaveCount(1)
    visited.add((await panel.getAttribute('data-project-slug'))!)
    await expect(panel).toContainText('Minha contribuição')
    await archive.getByRole('button', { name: 'Próximo projeto' }).click()
  }
  expect(visited.size).toBe(count)
  expect([...visited]).toEqual(expect.arrayContaining(['pmi-sleep-5', 'omapkdex', 'omarchy-gcal', 'ia2-bloodmnist']))
})

test('tabs have roving focus, localized labels and reduced-motion transitions', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/en/')
  const carousel = page.getByRole('region', { name: 'Projects', exact: true }).and(page.locator('[data-squeeze-carousel]'))
  await expect(carousel).toHaveAttribute('data-sq-ready', 'true')
  const active = () => carousel.getByRole('tab', { selected: true })
  await active().focus()
  await active().press('ArrowRight')
  await expect(carousel).toHaveAttribute('data-sq-index', '1')
  await expect(active()).toBeFocused()
  await active().press('End')
  await expect(carousel).toHaveAttribute('data-sq-index', '3')
  await active().press('Home')
  await expect(active()).toHaveAccessibleName('Hindsight')
  await expect(active()).toHaveCSS('transition-duration', '0s')
  await expect(carousel.getByRole('button', { name: 'Next project' })).toBeVisible()
  await expect(carousel.locator('[role="tab"][tabindex="0"]')).toHaveCount(1)
})

test('mobile panels fit at 320px and support a horizontal swipe', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/')
  const carousel = page.locator('[data-squeeze-carousel]').first()
  await expect(carousel).toHaveAttribute('data-sq-ready', 'true')
  await carousel.scrollIntoViewIfNeeded()
  const box = await carousel.getByRole('tab', { selected: true }).boundingBox()
  expect(box!.width).toBeGreaterThan(200)
  expect(box!.x + box!.width).toBeLessThanOrEqual(320)
  await carousel.locator('.sq-strip').dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 250, clientY: 100 }] })
  await carousel.locator('.sq-strip').dispatchEvent('touchend', { changedTouches: [{ identifier: 1, clientX: 90, clientY: 110 }] })
  await expect(carousel).toHaveAttribute('data-sq-index', '1')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
})

test('all projects and the Lab remain usable without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false })
  const page = await context.newPage()
  await page.goto('/')
  await expect(page.locator('[data-sq-panel]')).toHaveCount(15)
  await expect(page.locator('.sq-filters')).not.toBeVisible()
  await expect(page.locator('[data-lab-trigger]')).not.toBeVisible()
  for (const panel of await page.locator('[data-sq-panel]').all()) await expect(panel).toBeVisible()
  await page.locator('.embedded-lab summary').click()
  await expect(page.locator('.telemetry-path')).toBeVisible()
  await expect(page.locator('[data-project-slug="baja-telemetry-api"] a')).toHaveAttribute('href', 'https://github.com/UnBajaSAE/baja-telemetry-api')
  await context.close()
})

test('filters reset selection, preserve unique content and support the old hash', async ({ page }) => {
  for (const [path, featuredLabel, allLabel] of [['/', 'Destaques', 'Todos os projetos'], ['/en/', 'Featured', 'All projects']]) {
    await page.goto(`${path}#outros-projetos`)
    const carousel = page.locator('[data-squeeze-carousel]')
    await expect(carousel).toHaveCount(1)
    await expect(carousel).toHaveAttribute('data-sq-filter', 'all')
    await expect(carousel.locator('[data-sq-counter]')).toHaveText('01 / 15')
    const slugs = await page.locator('[data-project-slug]').evaluateAll(nodes => nodes.map(node => node.getAttribute('data-project-slug')))
    expect(new Set(slugs).size).toBe(17)
    expect(slugs).toHaveLength(17)
    const featured = carousel.getByRole('button', { name: featuredLabel, exact: true })
    await featured.click()
    await expect(featured).toHaveAttribute('aria-pressed', 'true')
    await expect(carousel.locator('[data-sq-counter]')).toHaveText('01 / 04')
    await carousel.getByRole('tab', { selected: true }).press('End')
    await expect(carousel.getByRole('tabpanel')).toHaveAttribute('data-project-slug', 'extracao-rda')
    await carousel.getByRole('button', { name: allLabel, exact: true }).click()
    await expect(carousel.locator('[data-sq-counter]')).toHaveText('01 / 15')
    await expect(carousel.getByRole('tabpanel')).toHaveAttribute('data-project-slug', 'hindsight')
    await featured.click()
    await page.evaluate(() => { location.hash = '#projetos' })
    await page.evaluate(() => { location.hash = '#outros-projetos' })
    await expect(carousel).toHaveAttribute('data-sq-filter', 'all')
  }
})

test('Lab closes from inside with focus restoration and survives rapid toggles', async ({ page }) => {
  await page.goto('/')
  const trigger = page.locator('[data-lab-trigger]')
  const lab = page.locator('.embedded-lab')
  await trigger.click()
  await expect(trigger).toHaveAccessibleName('Recolher Lab')
  await page.locator('[data-lab-close]').click()
  await expect(trigger).toBeFocused()
  await expect(lab).not.toHaveAttribute('open')
  await trigger.press('Space')
  await trigger.press('Space')
  await trigger.press('Space')
  await expect(lab).toHaveAttribute('open', '')
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await page.evaluate(() => { location.hash = '#embedded-projects' })
  await expect(lab).toHaveAttribute('open', '')
})

test('refined layout fits both themes, key widths and enlarged text', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.locator('[data-lab-trigger]').click()
    for (const theme of ['light', 'dark']) {
      await page.evaluate(value => { document.documentElement.dataset.theme = value }, theme)
      expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
      await expect(page.locator('[data-lab-close]')).toBeVisible()
    }
    await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    // ResizeObserver reflows the fixed-width carousel panels after text scaling.
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
  }
})
